export const ADD = "ADD";
export const EDIT = "EDIT";
export const ADDBRANDFILTER = "ADDBRANDFILTER";
export const ADDGENDERFILTER = "ADDGENDERFILTER";
export const SET_PRODUCT_CLICKED = "SETPRODUCTCLICKED"